generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: Employment
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: employment
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        company_id: {label: Compa&ntilde;&iacute;a }
        ocupation: {label: Ocupaci&oacute;n  }
        years: {label: A&ntilde;os, help: A&ntilde;os que lleva en ese trabajo.}
        month_income: {label: Ingreso Mensual }
        fancy_date_time: {label: ' '}
        colorbox_close_enable: {label: ' '}
      list:
        display:
          - '=id'
          - client_id
          - company_id
          - ocupation
        sort:
          - id
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - id
          - address
          - ocupation
          - month_income
          - client_id
          - company_id
      form:
        display:
          Cliente: [cliente, client_id]
          Tiempo que dura el Empleo: [ date_start, date_end, fancy_date_time]
          Informaci&oacute;n del Empleo: [company_id, ocupation, month_income, colorbox_close_enable]
        class: EmploymentAdminForm
        fields: {  }
      edit: ~
      new: ~
