Content:
  Global:
    main:                   # the main module is required, and must not be removed.
      components:
        header:
        ajaxloader:
        centerfooter:
        notifications:
        logo:
        footer:
        myCustomMenu:
        myStyledList:
        userInfo:
        mainDashBoard:
        calendarsDashBoard:
        legend:
        tramitlegend:
        geolocalizador:
        dateRangeSelector:
        reportGraphViewer:
        reportListViewer:
        reportDashBoard:
        reportCore:
        reportDashBoardAutoToogle:
        assignDatesRangeSelector:
        horizontalSeparator: 
  Usuarios:
    dm_user:
    client:
      page: true
      name: Cliente|Clientes
      components:
        list: 
        geoClientsList:
        show: 
    agent:
      name: Agente|Agentes
      components:
        datesByAgent:
        list: 
    telemarker:
      name: Telemarcador|Telemarcadores
      components:
        datesByTelemarker:
        datesByTelemarkerChart:
    source:
      name: Fuente|Fuentes
    user_availability:
      name: Disponibilidad | Disponibilidad
      front: true
      admin: false
      components:
        changeAvailabilities:
          name: Cambiar disponibilidades
        availabilityCalendar:
          name: Calendario de Disponibilidad
  Propiedades:
    #property_list:
    #  name: T-RE+Prop| T-RE+Props
    zip_codes:
      name: Zip Code | Zip Codes
    address:
      name: Direcci&oacute;n | Direcciones 
    property_on_sell:
      name: Tribaldos REAL ESTATE | Tribaldos REAL ESTATE
    property: 
      name: Propiedad|Propiedades
    loan_rate_type:
      name: Tipo de Pago|Tipos de Pago
    property_use:
      name: Usos | Uso
    property_type:
      name: Tipo de propiedad | Tipos de Propiedad
    property_condition:
      name: Condici&oacute;n|Condiciones
    property_transaction:
      name: Transacci&oacute;n|Transacciones
    property_loan_time:
      name: Tipo de Pr&eacute;stamo|Tipos de Pr&eacute;stamos
    property_payment: 
      name: Hipoteca|Hipotecas 
      page: false
      front: false 
    #state:
    #  name: Estado|Estados
    #city:
    #  name: Ciudad|Ciudades
    #  components:
    #    datesByCity:
    #    datesByCityChart:
  Compañias:
    employment:
      name: Empleo|Empleos
      components:
        list:
    company:
      name: Compañia|Compañias
  Recepcion:
    incomming_call_inventrary:
      name: Inventario|Inventario
    incomming_call_active_mod:
      name: Active Mod | Active Mods
    incomming_call_real_state:
      name: Real Estate | Real Estate
    incomming_call_prospect:
      name: Prospecto | Prospectos
    incomming_call_reason:
      name: Razon de la llamada | Razones de llamadas
    incomming_call_usual_callers:
      name: Caller|Callers
    incomming_call:
      page: false
      front: false
      admin: false
      name: 'Llamadas entrantes'
      components:
        incommingCallDashboard:
        reportCallsPerMonthConfig:
        callsPerMonthGraph:
        callsPerMonthList:
        reportCallsPerDayConfig:
        callsPerDayGraph:
        callsPerDayList:
        reportCallsPerReasonConfig:
        callsPerReasonGraph:
        callsPerReasonList:
        historyDatesRangeSelector:
        clientList:
        externalAgentList:
        agentList:
        assessorList:
        internalAgentList:
        affiliateList:
        list:
  #Departamentos:
  #  department:
  #    name: Departamento|Departamentos
  Eventos:
    event_public:
      name: Evento P&uacute;blico|Eventos P&uacute;blicos
      page: false
      components:
        publicCalendarLeyend:
          name: Leyenda
        publicCalendar:
          name: Calendario Publico
    event_root:
      name: Privado &oacute; Recordatorio|Privados o Recordatorios
      page: false
      components:
        privateCalendar:
          name: Calendario Privado
        privateCalendarLegend:
          name: Leyenda
  Citas:
    client_file:
      page: false
      front: false
      admin: false
      components:
        list:
        fullcalendar:
    file_type:
      page: false
      front: false
      name: Servicio | Servicios
    document:
      front: false
      name: Documento|Documentos
    phraseology:
      name: Fraseolog&iacute;a | Freaseolog&iacute;as
      components:
        list:
    event:
      name: Cita|Citas
      page: true
      components:
        geoEventsList:
        fullcalendar:
        form:
        list:
        show:
        eventLegend:
          name: Legend
        reportDatesByCityConfig:
        reportDatesByAgentConfig:
        reportDatesByTelemarkerConfig:
        reportDatesByDayConfig:
        reportDatesByMonthConfig:
        perDayDateChart:
        perDayDateList:
        perAgentDateChart:
        perAgentDateList:
        perTelemarketerDateChart:
        perTelemarketerDateList:
        perMonthDateChart:
        perMonthDateList:
        agentAssignDates:
        agentAssignDatesWithRangeSelector:
    event_category:
      name: Categor&iacute;a|Categor&iacute;as
    event_status:
      name: Situaci&oacute;n|Situaciones
    event_feed_back:
      name: Feed Back|Feed Back
      page: false
      components:
        fbHistoryDatesRangeSelector:
        list:
  Contabilidad:
    bank:
      name: Banco|Bancos
    expense:
      name: Gasto|Gastos
    income:
      name: Ingreso|Ingresos
    client_expense:
      name: Gasto del cliente|Gastos del cliente
      page: false
      components:
        list:
    client_income:
      name: Ingresos del cliente
      components:
        list:
    asset:
      name: Activo|Activos
    client_asset:
      name: Activo del cliente|Activos del cliente
      components:
        list:
    #liabilities:
    #  name: Liabilities
    #client_liabilities:
    #  name: Client Liabilities
    #  components:
    #    list:
    #wallet:
    #  name: Cartera|Carteras

    #account:
    #  name: Cuenta|Cuentas

    #account_type:
    #  name: Tipo de cuenta|Tipos de cuenta

    #transaction:
    #  name: Transacción|Transacciones

    #automated_transaction:
    #  name: Transacción recurrente|Transacciones recurrentes

    #payee:
    #  name: Beneficiario|Beneficiarios

    #payment:
    #  name: Tipo de pago|Tipos de pago

    #category:
    #  name: Categoría|Categorías
      

    #advise:
    #  name: Asesoramiento

