Content:

  Global:
    main:                   # the main module is required, and must not be removed.
      components:
        header:
        ajaxloader:
        centerfooter:
        notifications:
        logo:
        footer:
        myCustomMenu:
        myStyledList:
        userInfo:
        mainDashBoard:
        legend:
        tramitlegend:
        geolocalizador:
        dateRangeSelector:
        incommingCallDashboard: 
        reportGraphViewer:
        reportListViewer:
        reportDashBoard:
        reportDatesByCityConfig:
        reportDatesByAgentConfig:
        reportDatesByTelemarkerConfig:
        reportCore:
        reportDashBoardAutoToogle:
        assignDatesRangeSelector:
  Usuarios:
    dm_user:
    affiliate: 
      page: false
      name: Afiliado|Afiliados 
      front: true
      components:
        list: 
    externalAgent: 
      page: false
      name: Agente Externo | Agentes Externos 
      front: true
      components:
        list: 
    assessor: 
      page: false
      name: Asesor|Asesores
      front: true
      components:
        list: 
    client:
      page: true
      name: Cliente|Clientes
      components:
        list: 
        geoClientsList:
        summary:
    agent:
      name: Agente|Agentes
      components:
        datesByAgent:
        list: 
    telemarker:
      name: Telemarcador|Telemarcadores
      components:
        datesByTelemarker:
        datesByTelemarkerChart:

    source:
      name: Fuente|Fuentes
      
  Localidad:
    property: 
      name: Propiedad|Propiedades
    house:
      name: Vivienda|Viviendas
    state:
      name: Estado|Estados
    city:
      name: Ciudad|Ciudades
      components:
        datesByCity:
        datesByCityChart:

  Bancos:
    bank:
      name: Banco|Bancos

  Compannias:
    company:
      name: Compannia|Compannias
    employment:
      name: Empleado|Empleados
      components:
        list:

  Contabilidad:
    expense:
      name: Gasto|Gastos
    income:
      name: Ingreso|Ingresos
    client_expenses:
      name: Gastos del cliente
      components:
        list:
    client_incomes:
      name: Ingresos del cliente
      components:
        list:
    asset:
      name: Activo|Activos
    client_assets:
      name: Activos del cliente
      components:
        list:
    liabilities:
      name: Liabilities
    client_liabilities:
      name: Client Liabilities
      components:
        list:
    advise:
      name: Asesoramiento

  Llamadas Entrantes:
    incomming_call_reason: 
      name: Razon de la llamada | Razones de llamadas    
    incomming_call:
      name: 'Llamadas entrantes'
      components: 
        historyDatesRangeSelector: 
        clientList:
        externalAgentList:
        agentList:
        assessorList: 
        internalAgentList:
        affiliateList:  
        list: 
  Departamentos: 
    department: 
      name: Departamento|Departamentos
  Procesamiento:
    client_file:
      page: true
      components:
        list:
        fullcalendar:
    file_type:
    comment:
      front: false
      name:  Comentario|Comentarios
  Calendario:
    phraseology: 
      name: Fraseolog&iacute;a | Freaseolog&iacute;as
      components: 
        list: 
    event:
      name: Evento|Eventos
      components:
        geoEventsList:
        fullcalendar:
        form:
        list:
        perDayDateChart:
        perMonthDateReport:
        agentAssignDates:
        agentAssignDatesWithRangeSelector: 
    event_category:
      name: Categoria|Categorias
    event_status:
      name: Situacion|Situaciones

