generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: Affiliate
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: affiliate
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        groups_list:
          label: Groups
        permissions_list:
          label: Permissions
        is_active:
          label: Active
        is_super_admin:
          label: 'Super admin'
        first_name: 
          label: 'Nombre del Contacto'		
        last_name: 
          label: 'Apellido del Contacto'		
        phone: 
          label: 'Telefono del Contacto'
        aff_company_id: 
          label: Compa&ntilde;&iacute;a		
        aff_source_id: 
          label: Fuente
        colorbox_close_enable:
          label: " "
      list:
        display:
          - first_name
          - last_name
          - phone
          - aff_company_id
          - aff_source_id
          - email
          - is_active
          - created_by
          - created_at
        sort:
          - created_at
          - desc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - username
          - is_active
          - email
          - algorithm
          - salt
          - password
          - last_login
          - forgot_password_code
          - first_name
          - last_name
          - phone
          - assigned_to
          - live_in
          - ssn
          - dob
          - aff_source_id
          - aff_company_id
          - created_at
          - updated_at
          - created_by
          - updated_by
      form:
        display:
          NONE: [username, password, password_again, email]
          'Informacion Personal': [first_name, last_name, phone, aff_company_id, aff_source_id, colorbox_close_enable]
          'Llamadas entrantes': [incomming_call_list]
        class: AffiliateAdminForm
        fields: {  }
      edit: ~
      new: ~
