generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: ClientExpense
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: client_expense
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        colorbox_close_enable: { label: ' '}
        client_id: { label: Cliente }
        expense_id: { label: Gasto }
        amount: { label: Monto }
        payment: { label: Pago }
        loan_time_id: { label: 'Amortizaci&oacute;n'}
        comments: { label: Comentarios }
        colorbox_close_enable: { label: ' '}
      list:
        display:
          - client_id
          - expense_id
          - loan_time_id
          - amount
          - comments
        sort:
          - id
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - id
          - client_id
          - expense_id
          - amount
          - payment
          - comments
          - loan_time_id
      form:
        display:
          Cliente: [cliente, client_id]
          Informaci&oacute;n del Gasto: [expense_id, payment, amount, loan_time_id, comments, colorbox_close_enable]
        class: ClientExpenseAdminForm
        fields: {  }
      edit: ~
      new: ~
