generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: Referidos
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: referidos
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        colorbox_close_enable: {label: " "}
      list:
        display:
          - '=id'
          - client_id
          - city_id
          - visit
        sort:
          - id
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - id
          - visit
          - client_id
          - description
          - city_id
          - visit
      form:
        display:
          NONE: [client_id, city_id, visit, colorbox_close_enable]
          Description: [description]
        class: ReferidosAdminForm
        fields: {  }
      edit: ~
      new: ~
