default:
  
  http_metas:
    content-type: text/html

  stylesheets:
    - markdown
    - form-expansion 

  javascripts:
    - admin
    - form-expansion-fix
    - enable-tooglable-fieldset

  has_layout:     true
  layout:         <?php echo dm::getDir() ?>/dmAdminPlugin/modules/dmAdmin/templates/layout