generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: CompanyRecurringExpenses
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: company_recurring_expenses
    with_doctrine_route: false
    config:
      actions: ~
      fields: {  }
      list:
        display:
          - '=id'
          - wallet_id
          - company_id
          - expense_id
          - amount
          - tax
          - payment
          
          - enabled
          - max_occurrences
#          - must_occurrences
#          - last_execution_date
#          - created_at
#          - updated_at
        sort:
          - created_at
          - desc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - id
          - enabled
          - wallet_id
          - company_id
          - expense_id
          - amount
          - tax
          - payment
          - every
          - unit
          - max_occurrences
#          - must_occurrences
          - next_on
          - last_execution_date
          - description
          - created_at
          - updated_at
      form:
        display:
          NONE: [enabled, wallet_id, company_id, expense_id, amount, tax, payment, max_occurrences, every, unit, next_on, last_execution_date]
          Description: [description]
        class: CompanyRecurringExpensesAdminForm
        fields: {  }
      edit: ~
      new: ~
