<?php

/**
 * Address
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    intranet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Address extends BaseAddress
{
    public function  __toString() {
        return sprintf('%s, %s %s %s, %s', $this->getAddress(), $this->getPlaceName(), $this->getStateCode(), $this->getZipCode(), $this->getCountryCode());
    }
}
