<?php

/**
 * Agent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    intranet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Agent extends BaseAgent
{
    public function getClientsQuery() {
        $q = Doctrine_Query::create()
        ->from('Client c')
        ->where('c.assigned_to = ?', $this->getId());

       return $q;
    }

    public function getClients() {
        return $this->getClientsQuery()->execute();
    }

    public function countClients() {
        return $this->getClientsQuery()->count();
    }
}