<?php

/**
 * ClientExpenseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClientExpenseTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClientExpenseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClientExpense');
    }
}