<?php

/**
 * ClientAssetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClientAssetTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClientAssetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClientAsset');
    }
}