<?php

/**
 * ClientIncomeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClientIncomeTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClientIncomeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClientIncome');
    }
}