<?php

/**
 * EventCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    intranet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class EventCategory extends BaseEventCategory
{
    public function getActiveEventsQuery()
    {
        $q = Doctrine_Query::create()
            ->from('Event e')
            ->where('e.category_id = ?', $this->getId());

        return Doctrine::getTable('Event')->addActiveEventsQuery($q);
    }

    public function getPossibleStatuses(){
    	return $this->EventStatus;
    }

}