<?php

/**
 * EventFeedBack
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    intranet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class EventFeedBack extends BaseEventFeedBack
{
    public function  __toString() {
        $tail = (strlen($this->getComments()) > 70)?'...':'';
        return substr($this->getComments(), 0, 70).$tail;
    }
}
