<?php

/**
 * EventStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    intranet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class EventStatus extends BaseEventStatus
{
	public static function getSuccessfullDateStatus(){
    	return Doctrine::getTable('EventStatus')->createQuery('s')
    			->where('s.name = ?','Cerrado')
    			->fetchOne();
    }
    public static function getAssignedStatus(){
    	return Doctrine::getTable('EventStatus')->createQuery('s')
    			->where('s.name = ?','Asignado')
    			->fetchOne();
    }
}