<?php

/**
 * IncommingCallRealState
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    intranet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class IncommingCallRealState extends BaseIncommingCallRealState
{
    public function  __toString() {
        return sprintf('Real Estate > %s: %s %s: %s',   $this->getIncommingCallUsualCallers(), $this->getFirstName(), $this->getLastName(), $this->getComments());
    }
}
