<?php

/**
 * IncommingCallProspect
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    intranet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class IncommingCallProspect extends BaseIncommingCallProspect
{
    public function  __toString() {
        return sprintf('Prospecto > %s: %s %s: %s', $this->getSource(), $this->getFirstName(), $this->getLastName(), $this->getComments());
    }
}
