<?php

/**
 * Phraseology
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    intranet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Phraseology extends BasePhraseology
{
	public function getSuccessfullDates(){
		return Doctrine::getTable('Phraseology')->createQuery('p')
		->leftJoin('p.Event e')
		->where('e.status_id = ?', EventStatus::getSuccessfullDateStatus()->getId())
		->andWhere('p.id = ?', $this->getId())
		->execute();
		
	} 
	public function getSuccessfullDatesCount(){
		return $this->getSuccessfullDates()->count();
	}
}