<?php

/**
 * PropertyPayment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    intranet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PropertyPayment extends BasePropertyPayment
{
    public function  __toString() {
        return sprintf('Nro: %s, $%s - %s x %s a&ntilde;os al %s %s', $this->getLoanNr(),$this->getPayment(), $this->getLoanRateType(),$this->getPropertyLoanTime(), $this->getTasa(), '%');
    }
}
