<?php

/**
 * Telemarker
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    intranet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Telemarker extends BaseTelemarker
{
     public function  save(Doctrine_Connection $conn = null) {
        parent::save($conn);
        // adding user to telemarketer default group by default
        if (!$this->hasGroup('telemarcador')){
            $group = Doctrine::getTable('DmGroup')->findByName('telemarcador');
            if (count($group) <= 0)
            {
                $g = Doctrine::getTable('DmGroup')->create(array('name'=>'telemarcador', 'description'=>'Todos los telemarcadores'));
                $g->save();
            }
            
            $this->addGroupByName('telemarcador');
        }
    }
    public function  __toString() {
        return 'tm. '.$this->getFirstName().' '.$this->getLastName();
    }
}