generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: Event
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: event
    with_doctrine_route: false
    config:
      actions: ~ 
      fields:
        fancy_date_time:
          label: " "
        colorbox_close_enable:
          label: " "
        category_id:
          help: De qu&eacute; tipo es este evento?
          label: Categor&iacute;a
        status_id:
          help: En qu&eacute; fase se encuentra este evento?
          label: Estado
        description:
          label: Descripci&oacute;n
        asigned:
          label: Asignado a
        dm_user_id:
          label: Asignado a
        client_id: 
          label: Cliente
        date_start:
          label: Fecha Inicio
        date_end:
          label: Fecha fin
        description:
          label: Comentarios
        service_id:
          label: Servicio
        document_list:
          label: Documentos recogidos
        new_client:
          label: 'Nuevo '
        new_property:
          label: 'Nueva '
        property_id:
          label: Propiedad
        Address:
          label: 'Direcci&oacute;n de la cita'
          help: Dejar en blanco en caso de coincidir con la de la Propiedad
        signed_document_list:
          label: Documentos Firmados
        getted_document_list:
          label: Documentos Recogidos
      list:
        display:
          - '=description'
          - status_id
          - created_at
          - date_start
          - created_by
          - asigned
        sort:
          - dm_user_id
          - desc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - details
          - category_id
          - status_id
          - date_start
          - date_end
          - created_at
          - updated_at
      form:
        display:
          Cliente: [cliente, client_id, new_client, propiedad,property_id, new_property]
          Seleccion de Fecha y Hora: [fancy_date_time]
          Informaci&oacute;n del evento: [  category_id, status_id,  date_start, date_end, phraseology_id,   dm_user_id, service_id, Address, description,colorbox_close_enable, _timeFocusAvoider, _adminEventAutocompleterTooltips]
          Feed Back: [ getted_document_list, signed_document_list, event_feed_back_list ]
        class: EventAdminForm
        fields: {  }
      edit: 
        actions: 
          _list: 
            title: Volver al listado 
          _save: 
            title: Guardar este evento
          _save_and_add: 
            title: Guardar y adiciona otro
          _save_and_list: 
            title: Guardar y volver a la lista
          _save_and_next: 
            title: Guardar y siguiente
          _delete: 
            title: Borrar este evento
          _add: 
            title: Adicionar un evento		  
          _history: 
            title: Historial de cambios del evento
      new: 
        actions: 
          _list: 
            title: Volver al listado 
          _save: 
            title: Guardar este evento
          _save_and_add: 
            title: Guardar y adiciona otro
          _save_and_list: 
            title: Guardar y volver a la lista
          _save_and_next: 
            title: Guardar y siguiente
