generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: Property
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: property
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        colorbox_close_enable: { label: ' ' }
        client_id: { label: Cliente }
        Address:  { label: Direcci&oacute;n }
        parcel:   { label: Parcela }
        rooms_number: { label: Cuartos }
        bath_rooms_number: { label: 'Ba&ntilde;os' }
        property_use_id: { label: Uso }
        property_type_id: { label: Tipo }
        year_built: { label: 'A&ntilde;o de const.', help: 'A&ntilde;o en que se construy&oacute; la vivienda.'}
        years_on_property: { label: 'A&ntilde;os en la prop.' }
        people_on_property: { label: Personas en la prop.}
        refinantied_year: { label: '&Uacute;ltimo Refinanciamiento', help: 'A&ntilde;o del &uacute;ltimo refinanciamiento. Dejar en blanco si no se ha refinanciado.' }
        brought_year: { label: Fecha de Compra }
        rent_amount_received: { label: 'Recibe por renta?', help: Cu&aacute;nto recibe por la renta de la casa. Dejar en blanco si no se renta. }
        estimated_current_value: {label: Precio Estimado, help: 'Ej: 140000'}
        colorbox_close_enable: { label: ' '}
        sqft: { help: '&Aacute;rea construida en pies cuadrados. Ej: 1200' }
        
      list:
        display:
          - '=client_id'
          - '=Address'
          - parcel
          - rooms_number
          - bath_rooms_number
          - sqft
          - lote
          - year_built
        sort:
          - client_id
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - client_id
          - Address
          - parcel
          - rooms_number
          - bath_rooms_number
          - sqft
          - lote
          - year_built
          - years_on_property
          - people_on_property
          - rent_amount_received
          - property_type_id
          - property_use_id
          - tasa
      form:
        display:
          Cliente: [ cliente, client_id]
          Informaci&oacute;n de la propiedad: [Address,  parcel, rooms_number, bath_rooms_number,  sqft, lote, year_built, years_on_property, people_on_property,  brought_year, modified_year, estimated_current_value, property_use_id, property_type_id, rent_amount_received, colorbox_close_enable]
          Hipotecas: [ property_payment_list ]
        class: PropertyAdminForm
        fields: {  }
      edit: ~
      new: ~
