generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: Property
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: property
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        colorbox_close_enable: { label: " " }
        is_the_property_being_modified:
          label: Modified?
          help: Ha sido esta propiedad modificada antes?
      list:
        display:
          - '=id'
          - client_id
          - house_id
          - bank_id
          - mortgage_payment
          - rent_amount_received
          - is_the_property_being_modified
        sort:
          - id
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - id
          - client_id
          - house_id
          - bank_id
          - mortgage_payment
          - rent_amount_received
          - is_the_property_being_modified
          - years_on_property
          - people_on_property
          - use_of_property
          - type_of_property
      form:
        display:
          NONE: [client_id, house_id, bank_id, mortgage_payment, rent_amount_received, years_on_property, people_on_property, use_of_property, type_of_property, is_the_property_being_modified]
        class: PropertyAdminForm
        fields: {  }
      edit: ~
      new: ~
