generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: ClientExpenses
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: client_expenses
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        colorbox_close_enable: { label: ' '}
        client_id: { label: Cliente }
        expense_id: { label: Tipo de Gasto }
        amount: { label: Monto }
        payment: { label: Pago }
        payment_recurrence: { label: Recurrencia }
        comments: { label: Comentarios }
        colorbox_close_enable: { label: ' '}
      list:
        display:
          - '=id'
          - client_id
          - expense_id
          - amount
          - payment
          - payment_recurrence
          - comments
        sort:
          - id
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - id
          - client_id
          - expense_id
          - amount
          - payment
          - payment_recurrence
          - comments
      form:
        display:
          Cliente: [cliente, client_id]
          Informaci&oacute;n del Gasto: [expense_id, amount, payment, payment_recurrence, comments, colorbox_close_enable]
        class: ClientExpensesAdminForm
        fields: {  }
      edit: ~
      new: ~
