generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: Comment
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: comment
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        is_active:
          label: Active
        dm_user_id:
          label: Creado por
        colorbox_close_enable:
          label: " "
      list:
        display:
          - '=dm_user_id'
          - client_file_id
          - '=text'
          - is_active
          - created_at
          - updated_at
        sort:
          - created_at
          - desc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - dm_user_id
          - is_active
          - client_file_id
          - text
          - created_at
          - updated_at
      form:
        display:
          NONE: [dm_user_id, client_file_id, text, colorbox_close_enable]
        class: CommentAdminForm
        fields: {  }
      edit: ~
      new: ~
