generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: PropertyUse
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: property_use
    with_doctrine_route: false
    config:
      actions: ~
      fields: {  }
      list:
        display:
          - '=name'
          - property_list
        sort:
          - name
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - name
      form:
        display:
          NONE: [name]
          Propiedades: [property_list]
        class: PropertyUseAdminForm
        fields: {  }
      edit: ~
      new: ~
