generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: IncommingCall
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: incomming_call
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        tags_list:
          label: Tags
        dm_user_id:        { label: Cliente }
        time_in_min:      { label: Tiempo, help: Tiempo aproximado que duró la llamada en minutos }
        tags: { help: Palabras claves de la llamada}
        reason_id: {label: Razon de llamada}
        colorbox_close_enable: 
          label: " "
      list:
        display:
          - dm_user_id
          - '=reason_id'
          - created_by
          - created_at
        sort:
          - created_at
          - desc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - dm_user_id
          - time_in_min
          - description
          - created_at
          - updated_at
          - created_by
          - updated_by
      form:
        display:
          NONE: [dm_user_id, reason_id, description, colorbox_close_enable]
          Tags: [tags]
        class: IncommingCallAdminForm
        fields: {  }
      edit: ~
      new: ~
