generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: Assessor
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: assessor
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        groups_list:
          label: Groups
        permissions_list:
          label: Permissions
        is_active:
          label: Active
        is_super_admin:
          label: 'Super admin'
        colorbox_close_enable:
          label: ' '
      list:
        display:
          - '=username'
          - first_name
          - last_name
          - email
          - phone
          - company_id
          - source_id
          - incomming_call_list
        sort:
          - created_at
          - desc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - username
          - is_active
          - is_super_admin
          - email
          - algorithm
          - salt
          - password
          - last_login
          - forgot_password_code
          - first_name
          - last_name
          - phone
          - assigned_to
          - live_in
          - ssn
          - dob
          - source_id
          - company_id
          - created_at
          - updated_at
          - created_by
          - updated_by
      form:
        display:
          Datos Personales: [first_name, last_name, email, phone, assigned_to, company_id,  source_id, colorbox_close_enable]
          Comentarios: [comment_list]
          'Llamadas entrantes': [incomming_call_list]
          Groups: [groups_list]
          Permissions: [permissions_list]
        class: AssessorAdminForm
        fields: {  }
      edit: ~
      new: ~
