generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: ExternalAgent
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: external_agent
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        groups_list:
          label: Groups
        permissions_list:
          label: Permissions
        is_active:
          label: Active
        is_super_admin:
          label: 'Super admin'
        extag_company_id: 
          help: Compa&ntilde;&iacute;a para la que trabaja el agente.
          label: Compa&ntilde;&iacute;a 
        extag_source_id: 
          help: C&oacute;mo se enter&oacute; el agente.
          label: Fuente 
        phone: 
          label: Tel&eacute;fono del agente.
        first_name: 
          label: Nombre del agente.
        last_name: 
          label: Apellido del agente.
        email: 
          label: Email del agente.
        colorbox_close_enable:
          label: " "
      list:
        display:
          - '=first_name'
          - '=last_name'
          - created_by
          - extag_company_id
          - extag_source_id
          - email
          - is_active
          - phone
          - created_at
        sort:
          - created_at
          - desc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - '=username'
          - first_name
          - last_name
          - email
          - phone
          - company_id
          - source_id
          - incomming_call_list
      form:
        display:
          Informacion de agente externo: [ first_name, last_name, email, phone, extag_company_id, extag_source_id, colorbox_close_enable]
          'Llamadas entrantes': [incomming_call_list]
          Comentarios: [comment_list]
        class: ExternalAgentAdminForm
        fields: {  }
      edit: ~
      new: ~
