generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: Category
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: category
    with_doctrine_route: false
    config:
      actions: ~
      fields: {  }
      list:
        display:
          - '=name'
          - wallet_id
          - transaction_list
          - income
          - parent_category
        sort:
          - name
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - name
          - income
          - wallet_id
          - parent_category
      form:
        display:
          NONE: [name, income, wallet_id]
          Transacciones: [transaction_list]
          Others: [parent_category]
        class: CategoryAdminForm
        fields: {  }
      edit: ~
      new: ~
