generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: Department
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: department
    with_doctrine_route: false
    config:
      actions: ~
      fields: {  }
      list:
        display:
          - '=name'
          - client_file_list
        sort:
          - name
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - name
      form:
        display:
          NONE: [name]
          'Client files': [client_file_list]
        class: DepartmentAdminForm
        fields: {  }
      edit: ~
      new: ~
