generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: ClientIncomes
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: client_incomes
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        client_id: { label: Cliente }
        income_id: { label: Ingreso }
        amount: { label: Monto }
        recurrence: { label: Recurrencia }
        comments: { label: Comentarios}
        colorbox_close_enable: { label: ' '}
      list:
        display:
          - '=id'
          - client_id
          - income_id
          - amount
          - recurrence
          - comments
        sort:
          - id
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - id
          - client_id
          - income_id
          - amount
          - recurrence
          - comments
      form:
        display:
          Cliente: [cliente, client_id, income_id]
          Informaci&oacute;n del ingreso: [amount, recurrence, comments, colorbox_close_enable]
        class: ClientIncomesAdminForm
        fields: {  }
      edit: ~
      new: ~
