generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: Company
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: company
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        colorbox_close_enable: { label: " " }
        sector_id: { label: Sector }
        web_site:  { label: Sitio Web}
        Address: { label: ' '}
      list:
        actions: ~
        loremize: false
        display:
          - '=name'
          - Address
          - phone
          - fax
          - sector_id
        sort:
          - name
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - name
          - Address
          - phone
      form:
        display:
          Informaci&oacute;n de la Compa&ntilde;&iacute;a: [name, phone, fax, sector_id, web_site, Address, colorbox_close_enable]
        class: CompanyAdminForm
        fields: {  }
      edit: ~
      new: ~
