generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: Company
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: company
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        colorbox_close_enable: { label: " " }
      list:
        actions: ~
        loremize: false
        display:
          - '=name'
          - address
          - phone
        sort:
          - name
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - name
          - address
          - phone
      form:
        display:
          NONE: [name, address, phone, colorbox_close_enable]
        class: CompanyAdminForm
        fields: {  }
      edit: ~
      new: ~
