generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: EventPublic
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: event_public
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        category_id:
          label: Tipo de Evento
        tags_list:
          label: Tags
        is_active:
          label: Active
        is_new:
          label: New
        fancy_date_time:
          label: ' '
        colorbox_close_enable:
          label: ' '
      list:
        display:
          - '=id'
          - category_id
          - date_start
          - date_end
          - description
          - created_at
          - updated_at
        sort:
          - created_at
          - desc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - '=id'
          - category_id
          - date_start
          - date_end
          - description
          - created_at
          - updated_at
      form:
        display:
          Seleccion de Fecha y Hora: [date_start, date_end, fancy_date_time]
          Informacion del Evento: [title, category_id, description, colorbox_close_enable]
        class: EventPublicAdminForm
        fields: {  }
      edit: ~
      new: ~
