generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: ActiveListing
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: active_listing
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        colorbox_close_enable: { label: " " }
      list:
        display:
          - '=client_id'
          - property_id
          - description
          - agent
          - buyer
          - thirparty
        sort:
          - created_at
          - desc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - client_id
          - property_id
          - description
          - agent
          - buyer
          - thirparty
      form:
        display:
          NONE: [client_id, title, agent, buyer, thirparty, colorbox_close_enable, Property ]
          Description: [description]
        class: ActiveListingAdminForm
        fields: {  }
      edit: ~
      new: ~
