generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: Wallet
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: wallet
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        owner:  { label: Compañía }
        company_expenses_list: { label: Gastos }
        company_recurring_expenses_list: { label: 'Gastos recurrentes' }
      list:
        display:
          - '=id'
          - owner
          - company_expenses_list
          - company_recurring_expenses_list
        sort:
          - id
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - id
          - owner
      form:
        display:
          NONE: [owner, company_expenses_list, company_recurring_expenses_list]
        class: WalletAdminForm
        fields: {  }
      edit: ~
      new: ~
